import type { DailyPlan, MealSelection, PlanResult } from "./types";

/** Default times per meal period — close to UNC dining hall typical hours. */
const MEAL_TIMES: Record<
  "breakfast" | "lunch" | "dinner",
  { start: string; end: string }
> = {
  breakfast: { start: "08:00", end: "08:45" },
  lunch: { start: "12:30", end: "13:15" },
  dinner: { start: "18:00", end: "18:45" },
};

const DAY_INDEX: Record<string, number> = {
  Monday: 0,
  Tuesday: 1,
  Wednesday: 2,
  Thursday: 3,
  Friday: 4,
  Saturday: 5,
  Sunday: 6,
};

function pad(n: number): string {
  return n < 10 ? `0${n}` : String(n);
}

function nextMondayUTC(now = new Date()): Date {
  // Anchor the plan on the upcoming Monday so the user gets a clean week.
  const utc = new Date(
    Date.UTC(now.getFullYear(), now.getMonth(), now.getDate())
  );
  const dow = utc.getUTCDay(); // 0 = Sunday, 1 = Monday, ...
  const daysUntilMonday = (8 - dow) % 7 || 7;
  utc.setUTCDate(utc.getUTCDate() + daysUntilMonday);
  return utc;
}

function fmtDateTime(d: Date): string {
  return `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(
    d.getUTCDate()
  )}T${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}00Z`;
}

function escapeICSText(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/\n/g, "\\n")
    .replace(/,/g, "\\,")
    .replace(/;/g, "\\;");
}

function dateForDay(monday: Date, dayName: string): Date {
  const d = new Date(monday);
  const offset = DAY_INDEX[dayName] ?? 0;
  d.setUTCDate(d.getUTCDate() + offset);
  return d;
}

function timeOnDate(date: Date, hhmm: string): Date {
  const [hh, mm] = hhmm.split(":").map((s) => parseInt(s, 10));
  const out = new Date(date);
  // Convert local "12:30 PM Eastern" to UTC by adding 4 (EDT) or 5 (EST).
  // We use 4 (EDT, summer) which is the closer approximation for May; this
  // is intentionally rough — the user will see the events in their own TZ.
  out.setUTCHours(hh + 4, mm, 0, 0);
  return out;
}

interface CalendarEvent {
  uid: string;
  title: string;
  description: string;
  location: string;
  start: Date;
  end: Date;
}

function eventForMeal(
  meal: MealSelection,
  monday: Date,
  day: DailyPlan
): CalendarEvent | null {
  if (meal.period === "late_lunch") return null;
  const baseDate = dateForDay(monday, day.day);
  const window = MEAL_TIMES[meal.period];
  const start = timeOnDate(baseDate, window.start);
  const end = timeOnDate(baseDate, window.end);

  const lines: string[] = [
    `Location: ${meal.location}`,
    `Total: ${Math.round(meal.totals.calories)} kcal · ` +
      `${Math.round(meal.totals.proteinG)}g P / ` +
      `${Math.round(meal.totals.totalCarbsG)}g C / ` +
      `${Math.round(meal.totals.totalFatG)}g F`,
    "",
    "Order at the counter:",
    ...meal.items.map(
      (it) =>
        `• ${it.name} (${it.station}) — ${
          it.nutrition?.calories ?? 0
        } kcal, ${Math.round(it.nutrition?.proteinG ?? 0)}g protein`
    ),
    "",
    "Generated by Dinemate.",
  ];

  return {
    uid: `dinemate-${day.day}-${meal.period}-${start.getTime()}@dinemate.app`,
    title: `${
      meal.period.charAt(0).toUpperCase() + meal.period.slice(1)
    } @ ${meal.location}`,
    description: lines.join("\n"),
    location: meal.location,
    start,
    end,
  };
}

export function planToICS(plan: PlanResult): string {
  const monday = nextMondayUTC();
  const events: CalendarEvent[] = [];
  for (const day of plan.days) {
    for (const meal of day.meals) {
      const ev = eventForMeal(meal, monday, day);
      if (ev) events.push(ev);
    }
  }

  const dtstamp = fmtDateTime(new Date());
  const lines: string[] = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//Dinemate//UNC Meal Plan//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    "X-WR-CALNAME:Dinemate Meal Plan",
    "X-WR-TIMEZONE:America/New_York",
  ];
  for (const ev of events) {
    lines.push("BEGIN:VEVENT");
    lines.push(`UID:${ev.uid}`);
    lines.push(`DTSTAMP:${dtstamp}`);
    lines.push(`DTSTART:${fmtDateTime(ev.start)}`);
    lines.push(`DTEND:${fmtDateTime(ev.end)}`);
    lines.push(`SUMMARY:${escapeICSText(ev.title)}`);
    lines.push(`LOCATION:${escapeICSText(ev.location)}`);
    lines.push(`DESCRIPTION:${escapeICSText(ev.description)}`);
    lines.push("END:VEVENT");
  }
  lines.push("END:VCALENDAR");
  // RFC 5545 line endings.
  return lines.join("\r\n");
}

export function downloadICS(plan: PlanResult, filename = "dinemate-week.ics") {
  const ics = planToICS(plan);
  const blob = new Blob([ics], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
